require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlayedTricksController do

  # This should return the minimal set of attributes required to create a valid
  # PlayedTrick. As you add validations to PlayedTrick, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlayedTricksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all played_tricks as @played_tricks" do
      played_trick = PlayedTrick.create! valid_attributes
      get :index, {}, valid_session
      assigns(:played_tricks).should eq([played_trick])
    end
  end

  describe "GET show" do
    it "assigns the requested played_trick as @played_trick" do
      played_trick = PlayedTrick.create! valid_attributes
      get :show, {:id => played_trick.to_param}, valid_session
      assigns(:played_trick).should eq(played_trick)
    end
  end

  describe "GET new" do
    it "assigns a new played_trick as @played_trick" do
      get :new, {}, valid_session
      assigns(:played_trick).should be_a_new(PlayedTrick)
    end
  end

  describe "GET edit" do
    it "assigns the requested played_trick as @played_trick" do
      played_trick = PlayedTrick.create! valid_attributes
      get :edit, {:id => played_trick.to_param}, valid_session
      assigns(:played_trick).should eq(played_trick)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlayedTrick" do
        expect {
          post :create, {:played_trick => valid_attributes}, valid_session
        }.to change(PlayedTrick, :count).by(1)
      end

      it "assigns a newly created played_trick as @played_trick" do
        post :create, {:played_trick => valid_attributes}, valid_session
        assigns(:played_trick).should be_a(PlayedTrick)
        assigns(:played_trick).should be_persisted
      end

      it "redirects to the created played_trick" do
        post :create, {:played_trick => valid_attributes}, valid_session
        response.should redirect_to(PlayedTrick.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved played_trick as @played_trick" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlayedTrick.any_instance.stub(:save).and_return(false)
        post :create, {:played_trick => {}}, valid_session
        assigns(:played_trick).should be_a_new(PlayedTrick)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlayedTrick.any_instance.stub(:save).and_return(false)
        post :create, {:played_trick => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested played_trick" do
        played_trick = PlayedTrick.create! valid_attributes
        # Assuming there are no other played_tricks in the database, this
        # specifies that the PlayedTrick created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlayedTrick.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => played_trick.to_param, :played_trick => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested played_trick as @played_trick" do
        played_trick = PlayedTrick.create! valid_attributes
        put :update, {:id => played_trick.to_param, :played_trick => valid_attributes}, valid_session
        assigns(:played_trick).should eq(played_trick)
      end

      it "redirects to the played_trick" do
        played_trick = PlayedTrick.create! valid_attributes
        put :update, {:id => played_trick.to_param, :played_trick => valid_attributes}, valid_session
        response.should redirect_to(played_trick)
      end
    end

    describe "with invalid params" do
      it "assigns the played_trick as @played_trick" do
        played_trick = PlayedTrick.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlayedTrick.any_instance.stub(:save).and_return(false)
        put :update, {:id => played_trick.to_param, :played_trick => {}}, valid_session
        assigns(:played_trick).should eq(played_trick)
      end

      it "re-renders the 'edit' template" do
        played_trick = PlayedTrick.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlayedTrick.any_instance.stub(:save).and_return(false)
        put :update, {:id => played_trick.to_param, :played_trick => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested played_trick" do
      played_trick = PlayedTrick.create! valid_attributes
      expect {
        delete :destroy, {:id => played_trick.to_param}, valid_session
      }.to change(PlayedTrick, :count).by(-1)
    end

    it "redirects to the played_tricks list" do
      played_trick = PlayedTrick.create! valid_attributes
      delete :destroy, {:id => played_trick.to_param}, valid_session
      response.should redirect_to(played_tricks_url)
    end
  end

end
